from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SCRIPT = Path(__file__).parents[1] / "scripts" / "portal_dev_reap.py"
SPEC = importlib.util.spec_from_file_location("portal_dev_reap", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
portal_dev_reap = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = portal_dev_reap
SPEC.loader.exec_module(portal_dev_reap)


def env_values(name: str, base: int) -> dict[str, str]:
    values = {
        "WORKTREE_NAME": name,
        "PUBLIC_ENV__WORKTREE_NAME": name,
    }
    for offset, key in enumerate(portal_dev_reap.PORT_FLAGS):
        values[key] = str(base + offset)
    return values


def target(kind: str, path: str, name: str, base: int) -> portal_dev_reap.Target:
    values = env_values(name, base)
    return portal_dev_reap.Target(
        kind=kind,
        path=Path(path),
        name=name,
        ports={key: values[key] for key in portal_dev_reap.PORT_FLAGS},
        env_values=values,
    )


class PortalDevReapTests(unittest.TestCase):
    def test_parse_lsof_listener_records(self) -> None:
        parsed = portal_dev_reap.parse_lsof_listeners(
            """p123
cprocess-compose
f9
n127.0.0.1:18001
n[::1]:18001
p456
cnode
n*:19002"""
        )
        self.assertEqual(parsed[123]["command"], "process-compose")
        self.assertEqual(parsed[123]["ports"], {18001})
        self.assertEqual(parsed[456]["ports"], {19002})

    def test_parse_env_requires_and_returns_complete_identity(self) -> None:
        values = env_values("feature-safe", 12000)
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            self.assertEqual(portal_dev_reap.parse_env_file(env_path), values)

    def test_parse_env_refuses_duplicate_ports(self) -> None:
        values = env_values("feature-collision", 13000)
        values["REDIS_PORT"] = values["POSTGRES_PORT"]
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            with self.assertRaisesRegex(
                portal_dev_reap.ReapError, "duplicate allocated ports"
            ):
                portal_dev_reap.parse_env_file(env_path)

    def test_owning_target_uses_most_specific_path(self) -> None:
        primary = portal_dev_reap.Target(
            kind="primary",
            path=Path("/repo/cms"),
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        trash = target("trash", "/repo/cms/.git/wt/trash/old", "old", 14000)
        owner = portal_dev_reap.owning_target(
            [primary, trash],
            "/repo/cms/.git/wt/trash/old/backend",
        )
        self.assertEqual(owner, trash)

    def test_audit_preserves_active_and_refuses_foreign_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 15000)
        collided = target("worktree", "/repo/cms.collided", "collided", 16000)
        orphan = target("trash", "/repo/cms/.git/wt/trash/orphan", "orphan", 17000)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=10,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start stale",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=20,
                ppid=1,
                command="process-compose",
                cwd=str(collided.path),
                identity="start collided",
                age="02:00",
                ports=(int(collided.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=21,
                ppid=10,
                command="redis-server",
                cwd=str(stale.path),
                identity="start foreign",
                age="03:00",
                ports=(int(collided.ports["REDIS_PORT"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=30,
                ppid=1,
                command="redis-server",
                cwd=str(orphan.path),
                identity="start orphan",
                age="04:00",
                ports=(int(orphan.ports["REDIS_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale, collided, orphan],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([root], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["primary"].classification, "active")
        self.assertTrue(reports["primary"].protected)
        self.assertEqual(reports["stale"].classification, "inactive")
        self.assertTrue(reports["stale"].actionable)
        self.assertEqual(reports["collided"].classification, "unknown")
        self.assertFalse(reports["collided"].actionable)
        self.assertEqual(reports["orphan"].classification, "deleted-checkout-orphan")
        self.assertTrue(reports["orphan"].actionable)

    def test_audit_allows_manager_controlled_nix_store_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17500)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=40,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start manager",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=41,
                ppid=40,
                command="worker-dashboard",
                cwd="/nix/store/example-worker-dashboard",
                identity="start worker",
                age="01:00",
                ports=(int(stale.ports["WORKER_DASHBOARD_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "inactive")
        self.assertTrue(reports["stale"].actionable)
        self.assertEqual(reports["stale"].manager_controlled_listeners[0]["pid"], 41)

    def test_audit_refuses_process_compose_on_an_unexpected_port(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17600)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=50,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start mismatched manager",
                age="01:00",
                ports=(19000,),
            )
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "unknown")
        self.assertFalse(reports["stale"].actionable)

    def test_cleanup_command_passes_the_validated_identity(self) -> None:
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        with mock.patch.object(
            portal_dev_reap, "require_tool", return_value="/nix/bin/nix"
        ):
            command = portal_dev_reap.cleanup_command(stale)
        self.assertEqual(
            command[:4],
            ["/nix/bin/nix", "run", "/repo/cms.stale#portal-worktree-lifecycle", "--"],
        )
        self.assertIn("--pc-port-num", command)
        self.assertIn(stale.ports["PC_PORT_NUM"], command)


if __name__ == "__main__":
    unittest.main()
