from __future__ import annotations

import importlib.util
import io
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SCRIPT = Path(__file__).parents[1] / "scripts" / "portal_dev_reap.py"
SPEC = importlib.util.spec_from_file_location("portal_dev_reap", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
portal_dev_reap = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = portal_dev_reap
SPEC.loader.exec_module(portal_dev_reap)


def env_values(name: str, base: int) -> dict[str, str]:
    values = {
        "WORKTREE_NAME": name,
        "PUBLIC_ENV__WORKTREE_NAME": name,
    }
    for offset, key in enumerate(portal_dev_reap.PORT_FLAGS):
        values[key] = str(base + offset)
    return values


def target(kind: str, path: str, name: str, base: int) -> portal_dev_reap.Target:
    values = env_values(name, base)
    return portal_dev_reap.Target(
        kind=kind,
        path=Path(path),
        name=name,
        ports={key: values[key] for key in portal_dev_reap.PORT_FLAGS},
        env_values=values,
    )


def report(
    item: portal_dev_reap.Target,
    *,
    fingerprint: list[list[object]],
    actionable: bool = True,
    classification: str = "inactive",
) -> portal_dev_reap.TargetReport:
    return portal_dev_reap.TargetReport(
        kind=item.kind,
        path=str(item.path),
        name=item.name,
        pc_port=item.pc_port,
        classification=classification,
        runtime="running",
        actionable=actionable,
        protected=False,
        reasons=[],
        listeners=[],
        foreign_listeners=[],
        manager_controlled_listeners=[],
        extra_owned_listeners=[],
        fingerprint=fingerprint,
    )


def audit(
    reports: list[portal_dev_reap.TargetReport],
    *,
    protected_paths: list[str] | None = None,
) -> portal_dev_reap.Audit:
    return portal_dev_reap.Audit(
        schema_version=2,
        repository="/repo/cms",
        active_source="herdr-local-machine-all-running-sessions",
        active_error=None,
        active_paths=[],
        protected_paths=protected_paths or [],
        targets=reports,
        unknown_process_compose=[],
    )


# Host probes build_audit would otherwise run against the real machine.
HOST_PROBES = {
    "process_snapshot": {},
    "agent_checkouts": [],
    "checkout_evidence": {},
    "stack_health": [],
    "system_pressure": {},
}
REAL = {name: getattr(portal_dev_reap, name) for name in HOST_PROBES}
MERGED_CLEAN = {"branch": "fix/done", "head": "abc", "dirty": 0, "pr_number": 7,
                "pr_state": "MERGED", "pr_contains_head": True}


def unresolved_discovery(*suggested: str) -> portal_dev_reap.Discovery:
    return portal_dev_reap.Discovery(
        error=portal_dev_reap.UNRESOLVED_ERROR,
        unresolved=[{"workspace": "ios", "suggested_paths": list(suggested),
                     "resolve_with": "--associate default/w1:p1=/exact/checkout"}],
    )


class PortalDevReapTests(unittest.TestCase):
    def setUp(self) -> None:
        self.probes = {}
        for name, value in HOST_PROBES.items():
            patcher = mock.patch.object(portal_dev_reap, name, return_value=value)
            self.probes[name] = patcher.start()
            self.addCleanup(patcher.stop)

    def running_stack(self, discovery, **kwargs):
        """Audit one running linked checkout with a healthy manager."""
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        manager = portal_dev_reap.ProcessRef(123, 1, "process-compose", str(stale.path),
                                            "stable identity", "10-00:00:00", (18001,))
        with mock.patch.object(portal_dev_reap, "discover_targets", return_value=[stale]), \
             mock.patch.object(portal_dev_reap, "listener_processes", return_value=[manager]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=discovery):
            result, _ = portal_dev_reap.build_audit(Path("/repo/cms"), **kwargs)
        return result.targets[0]

    def test_parse_lsof_listener_records(self) -> None:
        parsed = portal_dev_reap.parse_lsof_listeners(
            """p123
cprocess-compose
f9
n127.0.0.1:18001
n[::1]:18001
p456
cnode
n*:19002"""
        )
        self.assertEqual(parsed[123]["command"], "process-compose")
        self.assertEqual(parsed[123]["ports"], {18001})
        self.assertEqual(parsed[456]["ports"], {19002})

    def test_parse_env_requires_and_returns_complete_identity(self) -> None:
        values = env_values("feature-safe", 12000)
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            self.assertEqual(portal_dev_reap.parse_env_file(env_path), values)

    def test_parse_env_refuses_duplicate_ports(self) -> None:
        values = env_values("feature-collision", 13000)
        values["REDIS_PORT"] = values["POSTGRES_PORT"]
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            with self.assertRaisesRegex(
                portal_dev_reap.ReapError, "duplicate allocated ports"
            ):
                portal_dev_reap.parse_env_file(env_path)

    def test_owning_target_uses_most_specific_path(self) -> None:
        primary = portal_dev_reap.Target(
            kind="primary",
            path=Path("/repo/cms"),
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        trash = target("trash", "/repo/cms/.git/wt/trash/old", "old", 14000)
        owner = portal_dev_reap.owning_target(
            [primary, trash],
            "/repo/cms/.git/wt/trash/old/backend",
        )
        self.assertEqual(owner, trash)

    def test_local_discovery_resolves_tasks_without_remote_queries_or_launch_history(self):
        roots = (Path("/repo/cms"), Path("/repo/cms.current"), Path("/repo/cms.old"))
        calls = []
        def command(argv, **kwargs):
            calls.append(argv)
            if argv[1:] == ["session", "list", "--json"]:
                value = {"sessions": [
                    {"name": "default", "running": True, "socket_path": "/local/default.sock"},
                    {"name": "second", "running": True, "socket_path": "/local/second.sock"},
                    {"name": "stopped", "running": False},
                ]}
            elif argv[1:] in (["--session", "default", "api", "snapshot"],
                               ["--session", "second", "api", "snapshot"]):
                value = {"result": {"snapshot": {
                    "workspaces": [{"workspace_id": "w1", "label": "current"}],
                    "agents": [{"pane_id": "w1:p1", "workspace_id": "w1", "terminal_id": "term1",
                                "agent_status": "idle", "cwd": str(roots[0])}],
                    # Same path on another machine must not enter local results.
                    "machines": [{"name": "remote", "cwd": str(roots[2])}],
                }}}
            else:
                raise AssertionError(f"unexpected/remote query: {argv}")
            return subprocess.CompletedProcess(argv, 0, json.dumps(value), "")
        with mock.patch.object(portal_dev_reap, "run", side_effect=command), \
             mock.patch.object(portal_dev_reap, "require_tool", side_effect=lambda name: name):
            result = portal_dev_reap.discover_active_work(roots, (
                "default/w1:p1=/repo/cms.current", "second/w1:p1=/repo/cms.current"))
        self.assertIsNone(result.error)
        self.assertEqual(result.paths, [roots[1]])
        self.assertEqual(len(result.evidence), 2)
        self.assertEqual({entry["socket"] for entry in result.evidence},
                         {"/local/default.sock", "/local/second.sock"})
        self.assertEqual(len(calls), 3)

    def test_audit_preserves_active_and_refuses_foreign_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 15000)
        collided = target("worktree", "/repo/cms.collided", "collided", 16000)
        orphan = target("trash", "/repo/cms/.git/wt/trash/orphan", "orphan", 17000)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=10,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start stale",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=20,
                ppid=1,
                command="process-compose",
                cwd=str(collided.path),
                identity="start collided",
                age="02:00",
                ports=(int(collided.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=21,
                ppid=10,
                command="redis-server",
                cwd=str(stale.path),
                identity="start foreign",
                age="03:00",
                ports=(int(collided.ports["REDIS_PORT"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=30,
                ppid=1,
                command="redis-server",
                cwd=str(orphan.path),
                identity="start orphan",
                age="04:00",
                ports=(int(orphan.ports["REDIS_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale, collided, orphan],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery(paths=[root])
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["primary"].classification, "active")
        self.assertTrue(reports["primary"].protected)
        self.assertEqual(reports["stale"].classification, "unknown")
        self.assertFalse(reports["stale"].actionable)
        self.assertEqual(reports["collided"].classification, "unknown")
        self.assertFalse(reports["collided"].actionable)
        self.assertEqual(reports["orphan"].classification, "unknown")
        self.assertFalse(reports["orphan"].actionable)

    def test_audit_allows_manager_controlled_nix_store_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17500)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=40,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start manager",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=41,
                ppid=40,
                command="worker-dashboard",
                cwd="/nix/store/example-worker-dashboard",
                identity="start worker",
                age="01:00",
                ports=(int(stale.ports["WORKER_DASHBOARD_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "unknown")
        self.assertFalse(reports["stale"].actionable)
        self.assertEqual(reports["stale"].manager_controlled_listeners[0]["pid"], 41)

    def test_audit_refuses_orphaned_unproven_dashboard_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17700)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=60,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start manager",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=61,
                ppid=1,
                command="worker-dashboard",
                cwd="/nix/store/example-worker-dashboard",
                identity="start orphan dashboard",
                age="01:00",
                ports=(int(stale.ports["WORKER_DASHBOARD_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap, "discover_targets", return_value=[primary, stale]
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
        ):
            result, _targets = portal_dev_reap.build_audit(root)

        stale_report = {item.name: item for item in result.targets}["stale"]
        self.assertEqual(stale_report.classification, "unknown")
        self.assertFalse(stale_report.actionable)
        self.assertEqual(stale_report.foreign_listeners[0]["pid"], 61)

    def test_explicit_protection_covers_work_not_visible_to_herdr(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        protected = target("worktree", "/repo/cms.protected", "protected", 17800)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=70,
                ppid=1,
                command="process-compose",
                cwd=str(protected.path),
                identity="start protected",
                age="01:00",
                ports=(int(protected.ports["PC_PORT_NUM"]),),
            )
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, protected],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
        ):
            result, _targets = portal_dev_reap.build_audit(
                root, (protected.path / "backend",)
            )

        protected_report = {item.name: item for item in result.targets}["protected"]
        self.assertEqual(protected_report.classification, "protected")
        self.assertTrue(protected_report.protected)
        self.assertFalse(protected_report.actionable)

    def test_explicit_protection_refuses_unmatched_path(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        with (
            mock.patch.object(
                portal_dev_reap, "discover_targets", return_value=[primary]
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=[]
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
            self.assertRaisesRegex(portal_dev_reap.ReapError, "protected path"),
        ):
            portal_dev_reap.build_audit(root, (Path("/repo/cms.typo"),))

    def test_auxiliary_port_change_keeps_ownership_fingerprint_stable(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)

        def build_with_ports(ports: tuple[int, ...]) -> portal_dev_reap.Audit:
            process = portal_dev_reap.ProcessRef(
                pid=80,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="same start and command",
                age="01:00",
                ports=ports,
            )
            with (
                mock.patch.object(
                    portal_dev_reap,
                    "discover_targets",
                    return_value=[primary, stale],
                ),
                mock.patch.object(
                    portal_dev_reap, "listener_processes", return_value=[process]
                ),
                mock.patch.object(
                    portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
                ),
            ):
                result, _targets = portal_dev_reap.build_audit(root, abandoned_paths=(stale.path,))
            return result

        pc_port = int(stale.ports["PC_PORT_NUM"])
        before = build_with_ports((pc_port, 28000))
        after = build_with_ports((pc_port, 28001, 28002))
        before_report = {item.name: item for item in before.targets}["stale"]
        after_report = {item.name: item for item in after.targets}["stale"]
        self.assertTrue(before_report.actionable)
        self.assertTrue(after_report.actionable)
        self.assertEqual(before_report.fingerprint, after_report.fingerprint)

    def test_task_replaced_in_same_pane_prevents_runtime_stop(self):
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        initial = audit([report(stale, fingerprint=[[81, "stable", str(stale.path)]])])
        initial.discovery.evidence = [{"pane": "w1:p1", "terminal_id": "original",
                                       "workspace": "current", "session": "default", "paths": ["/repo/cms.current"],
                                       "source": "reviewed task association"}]
        changed = portal_dev_reap.Discovery(evidence=[{**initial.discovery.evidence[0], "terminal_id": "replacement"}])
        with mock.patch.object(portal_dev_reap, "build_audit", return_value=(initial, {str(stale.path): stale})), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=changed), \
             mock.patch.object(portal_dev_reap, "run") as run_mock, \
             mock.patch("sys.stdout", new_callable=io.StringIO) as output, \
             mock.patch("sys.stderr", new_callable=io.StringIO):
            result = portal_dev_reap.apply_cleanup(root, initial)
        self.assertEqual(result, 1)
        self.assertIn("task identities/associations changed", output.getvalue())
        run_mock.assert_not_called()

    def test_discovery_lost_after_shutdown_is_reported_as_failure(self):
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        initial = audit([report(stale, fingerprint=[[81, "stable", str(stale.path)]])])
        stopped = report(stale, fingerprint=[], actionable=False)
        stopped.runtime = "stopped"
        final = audit([stopped])
        final.active_error = "Herdr unavailable"
        targets = {str(stale.path): stale}
        with mock.patch.object(portal_dev_reap, "build_audit", side_effect=[(initial, targets), (final, targets), (final, targets)]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()), \
             mock.patch.object(portal_dev_reap, "fingerprint_is_current", return_value=True), \
             mock.patch.object(portal_dev_reap, "cleanup_command", return_value=["cleanup"]), \
             mock.patch.object(portal_dev_reap, "run", return_value=subprocess.CompletedProcess([], 0)), \
             mock.patch("sys.stdout", new_callable=io.StringIO) as output:
            result = portal_dev_reap.apply_cleanup(root, initial)
        self.assertEqual(result, 1)
        self.assertIn("failed: final project discovery unavailable", output.getvalue())

    def test_apply_only_stops_selected_runtime_and_leaves_other_stale_stacks(self):
        root = Path("/repo/cms")
        first = target("worktree", "/repo/cms.first", "first", 18200)
        other = target("worktree", "/repo/cms.other", "other", 18300)
        selected = report(first, fingerprint=[[81, "first", str(first.path)]])
        unselected = report(other, fingerprint=[[82, "other", str(other.path)]])
        initial = audit([selected, unselected])
        stopped = report(first, fingerprint=[], actionable=False)
        stopped.runtime = "stopped"
        final = audit([stopped, unselected])
        targets = {str(first.path): first, str(other.path): other}
        with mock.patch.object(portal_dev_reap, "build_audit", side_effect=[(initial, targets), (final, targets), (final, targets)]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()), \
             mock.patch.object(portal_dev_reap, "fingerprint_is_current", return_value=True), \
             mock.patch.object(portal_dev_reap, "cleanup_command", side_effect=lambda item: ["cleanup", item.name]), \
             mock.patch.object(portal_dev_reap, "run", return_value=subprocess.CompletedProcess([], 0)) as run_mock, \
             mock.patch("sys.stdout", new_callable=io.StringIO):
            result = portal_dev_reap.apply_cleanup(root, initial, only=(first.path,))
        self.assertEqual(result, 0)
        self.assertEqual([call.args[0] for call in run_mock.call_args_list], [["cleanup", "first"]])

    def test_apply_skips_genuine_process_identity_replacement(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18100)
        initial = audit([report(stale, fingerprint=[[80, "old", str(stale.path)]])])
        changed = audit([report(stale, fingerprint=[[80, "new", str(stale.path)]])])
        final = audit(
            [
                report(
                    stale,
                    fingerprint=[[80, "new", str(stale.path)]],
                    actionable=False,
                    classification="unknown",
                )
            ]
        )
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[(changed, {str(stale.path): stale}), (final, {})],
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_apply_timeout_continues_without_retry_and_reports_results(self) -> None:
        root = Path("/repo/cms")
        first = target("worktree", "/repo/cms.first", "first", 18200)
        second = target("worktree", "/repo/cms.second", "second", 18300)
        first_report = report(first, fingerprint=[[81, "first", str(first.path)]])
        second_report = report(second, fingerprint=[[82, "second", str(second.path)]])
        initial = audit([first_report, second_report])
        fresh = audit([first_report, second_report])
        stopped = report(second, fingerprint=[], actionable=False)
        stopped.runtime = "stopped"
        final = audit([stopped])
        timeout = subprocess.TimeoutExpired(["nix", "run"], 180)
        succeeded = subprocess.CompletedProcess([], 0)
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(first.path): first, str(second.path): second}),
                    (fresh, {str(first.path): first, str(second.path): second}),
                    (final, {}),
                    (final, {}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
            mock.patch.object(
                portal_dev_reap, "fingerprint_is_current", return_value=True
            ),
            mock.patch.object(
                portal_dev_reap,
                "cleanup_command",
                side_effect=lambda item: ["cleanup", item.name],
            ),
            mock.patch.object(
                portal_dev_reap, "run", side_effect=[timeout, succeeded]
            ) as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO) as stdout,
            mock.patch("sys.stderr", new_callable=io.StringIO) as stderr,
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        self.assertEqual(run_mock.call_count, 2)
        self.assertIn("not retrying", stderr.getvalue())
        self.assertIn("failed: cleanup timed out", stdout.getvalue())
        self.assertIn("runtime stopped; checkout and data preserved", stdout.getvalue())

    def test_apply_skips_identity_replaced_after_batch_revalidation(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18350)
        stale_report = report(stale, fingerprint=[[84, "stable", str(stale.path)]])
        initial = audit([stale_report])
        fresh = audit([stale_report])
        final = audit([stale_report])
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(stale.path): stale}),
                    (final, {str(stale.path): stale}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
            mock.patch.object(
                portal_dev_reap, "fingerprint_is_current", return_value=False
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
            mock.patch("sys.stderr", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_apply_rechecks_herdr_before_each_cleanup(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18400)
        stale_report = report(stale, fingerprint=[[83, "stable", str(stale.path)]])
        initial = audit([stale_report])
        fresh = audit([stale_report])
        final = audit([stale_report])
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(stale.path): stale}),
                    (final, {str(stale.path): stale}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap,
                "discover_active_work",
                return_value=portal_dev_reap.Discovery(paths=[stale.path]),
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_audit_refuses_process_compose_on_an_unexpected_port(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17600)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=50,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start mismatched manager",
                age="01:00",
                ports=(19000,),
            )
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "unknown")
        self.assertFalse(reports["stale"].actionable)

    def test_cleanup_uses_installed_stop_instead_of_historical_removal(self):
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        with mock.patch.object(portal_dev_reap, "require_tool", side_effect=lambda name: name):
            command = portal_dev_reap.cleanup_command(stale)
        self.assertEqual(command, ["portal-worktree-lifecycle", "stop-runtime", "--worktree-path",
                                  str(stale.path), "--legacy-pc-port", stale.pc_port])

    def test_unresolved_primary_cwd_requires_review_even_when_old_launch_record_exists(self):
        with tempfile.TemporaryDirectory() as directory:
            primary, sibling = Path(directory).resolve()/"primary", Path(directory).resolve()/"sibling"
            primary.mkdir()
            (sibling/".data").mkdir(parents=True)
            (sibling/".data/portal-dev-manager-v1.json").write_text(json.dumps({
                "root": str(sibling), "herdr_sessions": [{"pane": "w1:p2", "socket": "/local/herdr.sock"}]}))
            def command(argv, **kwargs):
                if argv[1:] == ["session", "list", "--json"]:
                    value = {"sessions": [{"name": "default", "running": True, "socket_path": "/local/herdr.sock"}]}
                elif argv[1:] == ["--session", "default", "api", "snapshot"]:
                    value = {"result": {"snapshot": {
                        "workspaces": [{"workspace_id": "w1", "label": "ios"}],
                        "agents": [{"pane_id": "w1:p2", "workspace_id": "w1", "terminal_id": "term2",
                                    "agent_status": "blocked", "cwd": str(primary)}]}}}
                elif "read" in argv:
                    return subprocess.CompletedProcess(argv, 0, f"Working in {sibling}/docs", "")
                else:
                    raise AssertionError(argv)
                return subprocess.CompletedProcess(argv, 0, json.dumps(value), "")
            with mock.patch.object(portal_dev_reap, "run", side_effect=command), \
                 mock.patch.object(portal_dev_reap, "require_tool", side_effect=lambda name: name):
                unresolved = portal_dev_reap.discover_active_work((primary, sibling))
                reviewed = portal_dev_reap.discover_active_work((primary, sibling), (f"default/w1:p2={sibling}",))
                obsolete = portal_dev_reap.discover_active_work((primary, sibling), (f"default/w1:missing={sibling}",))
            self.assertIn("unresolved", unresolved.error)
            self.assertEqual(unresolved.paths, [])
            self.assertEqual(unresolved.unresolved[0]["suggested_paths"], [str(sibling)])
            self.assertIsNone(reviewed.error)
            self.assertEqual(reviewed.paths, [sibling.resolve()])
            self.assertIn("no longer matches", obsolete.error)

    def test_discovery_failure_never_authorizes_stale_cleanup(self):
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        manager = portal_dev_reap.ProcessRef(123, 1, "process-compose", str(stale.path),
                                            "stable identity", "10 days", (18001,))
        with mock.patch.object(portal_dev_reap, "discover_targets", return_value=[stale]), \
             mock.patch.object(portal_dev_reap, "listener_processes", return_value=[manager]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery(error="Herdr unavailable")):
            result, _ = portal_dev_reap.build_audit(Path("/repo/cms"), outside_active=True)
        self.assertEqual(result.targets[0].classification, "unknown")
        self.assertFalse(result.targets[0].actionable)
        with self.assertRaisesRegex(portal_dev_reap.ReapError, "Herdr unavailable"):
            portal_dev_reap.apply_cleanup(Path("/repo/cms"), result)

    def test_running_stale_stack_requires_explicit_abandonment_or_outside_active_policy(self):
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        manager = portal_dev_reap.ProcessRef(123, 1, "process-compose", str(stale.path),
                                            "stable identity", "10 days", (18001,))
        with mock.patch.object(portal_dev_reap, "discover_targets", return_value=[stale]), \
             mock.patch.object(portal_dev_reap, "listener_processes", return_value=[manager]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery(paths=[Path("/repo/cms")])):
            unknown, _ = portal_dev_reap.build_audit(Path("/repo/cms"))
            outside, _ = portal_dev_reap.build_audit(Path("/repo/cms"), outside_active=True)
            approved, _ = portal_dev_reap.build_audit(Path("/repo/cms"), abandoned_paths=(stale.path,))
            protected, _ = portal_dev_reap.build_audit(Path("/repo/cms"), (stale.path,), (stale.path,))
        self.assertEqual(unknown.targets[0].classification,"unknown")
        self.assertFalse(unknown.targets[0].actionable)
        self.assertTrue(approved.targets[0].actionable)
        self.assertEqual(outside.targets[0].classification, "stale")
        self.assertTrue(outside.targets[0].actionable)
        self.assertFalse(protected.targets[0].actionable)

    def test_process_snapshot_parses_identity_and_survives_malformed_rows(self):
        table = portal_dev_reap.parse_process_snapshot(
            "  10     1 Fri Oct  2 15:01:02 2026 13-03:53:44  18544 process-compose   --port 8081\n"
            "garbage row\n"
            "  11    10 Fri Oct  2 15:01:03 2026       00:39    512 postgres: idle\n"
        )
        self.assertEqual(set(table), {10, 11})
        self.assertEqual(table[10].ppid, 1)
        self.assertEqual(table[10].age, "13-03:53:44")
        self.assertEqual(table[10].rss_kb, 18544)
        self.assertEqual(portal_dev_reap.identity_of(table[10]),
                         "Fri Oct 2 15:01:02 2026 process-compose --port 8081")
        self.assertEqual(portal_dev_reap.descendants(table, {10}), {10, 11})

    def test_cwd_lookup_is_one_batched_call_and_a_timeout_is_not_fatal(self):
        listing = subprocess.CompletedProcess([], 1, "p10\nfcwd\nn/repo/cms.stale\np11\nfcwd\nn/nix/store/x\n", "")
        with mock.patch.object(portal_dev_reap, "run", return_value=listing) as run_mock, \
             mock.patch.object(portal_dev_reap, "canonical", side_effect=Path):
            cwds = portal_dev_reap.process_cwds("lsof", {11, 10, 12})
        self.assertEqual(cwds, {10: "/repo/cms.stale", 11: "/nix/store/x"})
        self.assertEqual(run_mock.call_count, 1)
        self.assertIn("10,11,12", run_mock.call_args.args[0])
        with mock.patch.object(portal_dev_reap, "run", side_effect=subprocess.TimeoutExpired(["lsof"], 60)):
            self.assertEqual(portal_dev_reap.process_cwds("lsof", {10}), {})

    def test_finished_pull_request_is_stoppable_despite_unresolved_herdr_tasks(self):
        self.probes["checkout_evidence"].return_value = dict(MERGED_CLEAN)
        merged = self.running_stack(unresolved_discovery())
        # Never "stale": that class is deletion authority for disk maintenance.
        self.assertEqual(merged.classification, "pr-merged")
        self.assertTrue(merged.actionable)
        self.assertTrue(merged.herdr_independent)

    def test_pull_request_evidence_must_be_complete_to_authorize_a_stop(self):
        for change in ({"dirty": 2}, {"pr_contains_head": False}, {"pr_state": "OPEN"},
                       {"pr_state": None, "pr_number": None}):
            self.probes["checkout_evidence"].return_value = {**MERGED_CLEAN, **change}
            with self.subTest(change=change):
                item = self.running_stack(unresolved_discovery())
                self.assertEqual(item.classification, "unknown")
                self.assertFalse(item.actionable)

    def test_finished_pull_request_does_not_override_possible_current_work(self):
        self.probes["checkout_evidence"].return_value = dict(MERGED_CLEAN)
        mentioned = self.running_stack(unresolved_discovery("/repo/cms.stale"))
        self.assertEqual(mentioned.classification, "unknown")
        self.assertFalse(mentioned.actionable)
        protected = self.running_stack(unresolved_discovery(), protected_paths=(Path("/repo/cms.stale"),))
        self.assertFalse(protected.actionable)
        self.probes["agent_checkouts"].return_value = [Path("/repo/cms.stale/frontend")]
        live = self.running_stack(unresolved_discovery())
        self.assertEqual(live.classification, "active")
        self.assertFalse(live.actionable)

    def test_reviewed_abandonment_survives_unresolved_tasks_but_not_failed_discovery(self):
        path = Path("/repo/cms.stale")
        reviewed = self.running_stack(unresolved_discovery(), abandoned_paths=(path,))
        self.assertEqual(reviewed.classification, "stale")
        self.assertTrue(reviewed.actionable)
        self.assertTrue(reviewed.herdr_independent)
        mentioned = self.running_stack(unresolved_discovery(str(path)), abandoned_paths=(path,))
        self.assertFalse(mentioned.actionable)
        failed = self.running_stack(portal_dev_reap.Discovery(error="Herdr unavailable"), abandoned_paths=(path,))
        self.assertEqual(failed.classification, "unknown")
        self.assertFalse(failed.actionable)

    def test_checkout_evidence_reads_git_state_and_prefers_an_open_pull_request(self):
        def command(argv, **kwargs):
            if "status" in argv:
                out = "# branch.oid abc\n# branch.head fix/done\n1 .M N... 1 1 1 a b file\n? new\n"
            elif "log" in argv:
                out = "0\n"
            elif argv[0] == "gh":
                self.assertIn("fix/done", argv)
                out = json.dumps([{"number": 7, "state": "MERGED", "headRefOid": "old"},
                                  {"number": 9, "state": "OPEN", "headRefOid": "abc"}])
            else:
                raise AssertionError(argv)
            return subprocess.CompletedProcess(argv, 0, out, "")
        with tempfile.TemporaryDirectory() as directory, \
             mock.patch.object(portal_dev_reap, "run", side_effect=command), \
             mock.patch.object(portal_dev_reap.shutil, "which", side_effect=lambda name: name):
            evidence = REAL["checkout_evidence"](Path(directory))
        self.assertEqual((evidence["branch"], evidence["dirty"]), ("fix/done", 2))
        self.assertEqual((evidence["pr_number"], evidence["pr_state"], evidence["pr_contains_head"]),
                         (9, "OPEN", True))
        self.assertIsNone(portal_dev_reap.evidence_class(evidence))
        self.assertEqual(portal_dev_reap.evidence_class(MERGED_CLEAN), "pr-merged")

    def test_checkout_behind_its_merged_pull_request_is_finished_but_local_commits_are_not(self):
        def evidence_when(ancestor_exit: int):
            def command(argv, **kwargs):
                if "status" in argv:
                    return subprocess.CompletedProcess(argv, 0, "# branch.oid local\n# branch.head fix/done\n", "")
                if "log" in argv:
                    return subprocess.CompletedProcess(argv, 0, "0\n", "")
                if argv[0] == "gh":
                    pulls = [{"number": 7, "state": "MERGED", "headRefOid": "remote"}]
                    return subprocess.CompletedProcess(argv, 0, json.dumps(pulls), "")
                self.assertEqual(argv[-4:], ["merge-base", "--is-ancestor", "local", "remote"])
                return subprocess.CompletedProcess(argv, ancestor_exit, "", "")
            with tempfile.TemporaryDirectory() as directory, \
                 mock.patch.object(portal_dev_reap, "run", side_effect=command), \
                 mock.patch.object(portal_dev_reap.shutil, "which", side_effect=lambda name: name):
                return REAL["checkout_evidence"](Path(directory))
        self.assertEqual(portal_dev_reap.evidence_class(evidence_when(0)), "pr-merged")
        self.assertIsNone(portal_dev_reap.evidence_class(evidence_when(1)))

    def test_stack_health_reports_crash_loops_and_dead_services(self):
        services = {"data": [
            {"name": "portal", "status": "Running", "restarts": 14686, "exit_code": 1, "system_time": "7s"},
            {"name": "cms-db", "status": "Completed", "restarts": 5, "exit_code": 1},
            {"name": "portal-migrate", "status": "Completed", "restarts": 0, "exit_code": 0},
            {"name": "redis", "status": "Running", "restarts": 1, "exit_code": 0},
        ]}
        opener = mock.Mock()
        opener.open.return_value = io.BytesIO(json.dumps(services).encode())
        with mock.patch.object(portal_dev_reap.urllib.request, "build_opener", return_value=opener):
            findings = REAL["stack_health"]("8081")
        self.assertEqual(findings, ["portal restarted 14686 times (current run: 7s)",
                                    "cms-db exited with code 1 and is not running"])
        opener.open.side_effect = OSError("refused")
        with mock.patch.object(portal_dev_reap.urllib.request, "build_opener", return_value=opener):
            self.assertIn("unreachable", REAL["stack_health"]("8081")[0])

    def test_protected_primary_stack_still_reports_health_and_cost(self):
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(kind="primary", path=root, name="primary",
                                         ports=dict(portal_dev_reap.PRIMARY_PORTS))
        manager = portal_dev_reap.ProcessRef(26515, 1, "process-compose", str(root),
                                            "stable identity", "13-03:54:08", (8081,))
        info = portal_dev_reap.ProcessInfo
        gone = "/nix/store/" + "a" * 32 + "-start-postgres/bin/start-postgres"
        self.probes["process_snapshot"].return_value = {
            26515: info(26515, 1, "start", "13-03:54:08", 20480, "process-compose --port 8081"),
            26600: info(26600, 26515, "start", "00:07", 102400, gone),
        }
        self.probes["stack_health"].return_value = ["portal restarted 14686 times (current run: 7s)"]
        with mock.patch.object(portal_dev_reap, "discover_targets", return_value=[primary]), \
             mock.patch.object(portal_dev_reap, "listener_processes", return_value=[manager]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=portal_dev_reap.Discovery()):
            result, _ = portal_dev_reap.build_audit(root)
        item = result.targets[0]
        self.assertEqual(item.classification, "protected")
        self.assertFalse(item.actionable)
        self.assertEqual(item.health[0], "portal restarted 14686 times (current run: 7s)")
        self.assertIn("garbage-collected", item.health[1])
        self.assertEqual((item.process_count, item.rss_mb, item.age), (2, 120, "13-03:54:08"))
        with mock.patch("sys.stdout", new_callable=io.StringIO) as output:
            portal_dev_reap.print_audit(result)
        self.assertIn("✗ portal restarted 14686 times", output.getvalue())
        self.assertIn("Unhealthy stacks: 1", output.getvalue())

    def test_apply_stops_herdr_independent_runtime_while_tasks_are_unresolved(self):
        root = Path("/repo/cms")
        merged = target("worktree", "/repo/cms.merged", "merged", 18200)
        blocked = target("worktree", "/repo/cms.blocked", "blocked", 18300)
        candidate = report(merged, fingerprint=[[81, "merged", str(merged.path)]], classification="pr-merged")
        candidate.herdr_independent = True
        other = report(blocked, fingerprint=[[82, "blocked", str(blocked.path)]],
                       actionable=False, classification="unknown")
        stopped = report(merged, fingerprint=[], actionable=False, classification="pr-merged")
        stopped.runtime = "stopped"
        initial, final = audit([candidate, other]), audit([stopped, other])
        initial.active_error = final.active_error = portal_dev_reap.UNRESOLVED_ERROR
        targets = {str(merged.path): merged, str(blocked.path): blocked}
        with mock.patch.object(portal_dev_reap, "build_audit", side_effect=[(initial, targets), (final, targets), (final, targets)]), \
             mock.patch.object(portal_dev_reap, "discover_active_work", return_value=unresolved_discovery()), \
             mock.patch.object(portal_dev_reap, "fingerprint_is_current", return_value=True), \
             mock.patch.object(portal_dev_reap, "cleanup_command", side_effect=lambda item: ["cleanup", item.name]), \
             mock.patch.object(portal_dev_reap, "run", return_value=subprocess.CompletedProcess([], 0)) as run_mock, \
             mock.patch("sys.stdout", new_callable=io.StringIO) as output:
            result = portal_dev_reap.apply_cleanup(root, initial)
        self.assertEqual(result, 0)
        self.assertEqual([call.args[0] for call in run_mock.call_args_list], [["cleanup", "merged"]])
        self.assertIn("runtime stopped; checkout and data preserved", output.getvalue())


if __name__ == "__main__":
    unittest.main()
