from __future__ import annotations

import importlib.util
import io
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SCRIPT = Path(__file__).parents[1] / "scripts" / "portal_dev_reap.py"
SPEC = importlib.util.spec_from_file_location("portal_dev_reap", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
portal_dev_reap = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = portal_dev_reap
SPEC.loader.exec_module(portal_dev_reap)


def env_values(name: str, base: int) -> dict[str, str]:
    values = {
        "WORKTREE_NAME": name,
        "PUBLIC_ENV__WORKTREE_NAME": name,
    }
    for offset, key in enumerate(portal_dev_reap.PORT_FLAGS):
        values[key] = str(base + offset)
    return values


def target(kind: str, path: str, name: str, base: int) -> portal_dev_reap.Target:
    values = env_values(name, base)
    return portal_dev_reap.Target(
        kind=kind,
        path=Path(path),
        name=name,
        ports={key: values[key] for key in portal_dev_reap.PORT_FLAGS},
        env_values=values,
    )


def report(
    item: portal_dev_reap.Target,
    *,
    fingerprint: list[list[object]],
    actionable: bool = True,
    classification: str = "inactive",
) -> portal_dev_reap.TargetReport:
    return portal_dev_reap.TargetReport(
        kind=item.kind,
        path=str(item.path),
        name=item.name,
        pc_port=item.pc_port,
        classification=classification,
        runtime="running",
        actionable=actionable,
        protected=False,
        reasons=[],
        listeners=[],
        foreign_listeners=[],
        manager_controlled_listeners=[],
        extra_owned_listeners=[],
        fingerprint=fingerprint,
    )


def audit(
    reports: list[portal_dev_reap.TargetReport],
    *,
    protected_paths: list[str] | None = None,
) -> portal_dev_reap.Audit:
    return portal_dev_reap.Audit(
        schema_version=2,
        repository="/repo/cms",
        active_source="herdr-local-machine-all-running-sessions",
        active_error=None,
        active_paths=[],
        protected_paths=protected_paths or [],
        targets=reports,
        unknown_process_compose=[],
    )


class PortalDevReapTests(unittest.TestCase):
    def test_parse_lsof_listener_records(self) -> None:
        parsed = portal_dev_reap.parse_lsof_listeners(
            """p123
cprocess-compose
f9
n127.0.0.1:18001
n[::1]:18001
p456
cnode
n*:19002"""
        )
        self.assertEqual(parsed[123]["command"], "process-compose")
        self.assertEqual(parsed[123]["ports"], {18001})
        self.assertEqual(parsed[456]["ports"], {19002})

    def test_parse_env_requires_and_returns_complete_identity(self) -> None:
        values = env_values("feature-safe", 12000)
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            self.assertEqual(portal_dev_reap.parse_env_file(env_path), values)

    def test_parse_env_refuses_duplicate_ports(self) -> None:
        values = env_values("feature-collision", 13000)
        values["REDIS_PORT"] = values["POSTGRES_PORT"]
        with tempfile.TemporaryDirectory() as directory:
            env_path = Path(directory) / ".env.worktree"
            content = ["# Auto-generated by worktrunk - do not edit"]
            content.extend(f'export {key}="{value}"' for key, value in values.items())
            env_path.write_text("\n".join(content) + "\n", encoding="utf-8")
            env_path.chmod(0o600)
            with self.assertRaisesRegex(
                portal_dev_reap.ReapError, "duplicate allocated ports"
            ):
                portal_dev_reap.parse_env_file(env_path)

    def test_owning_target_uses_most_specific_path(self) -> None:
        primary = portal_dev_reap.Target(
            kind="primary",
            path=Path("/repo/cms"),
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        trash = target("trash", "/repo/cms/.git/wt/trash/old", "old", 14000)
        owner = portal_dev_reap.owning_target(
            [primary, trash],
            "/repo/cms/.git/wt/trash/old/backend",
        )
        self.assertEqual(owner, trash)

    def test_herdr_inventory_covers_all_running_sessions_on_local_machine(self) -> None:
        completed = subprocess.CompletedProcess
        session_list = completed(
            [],
            0,
            stdout='{"sessions":[{"name":"default","running":true},'
            '{"name":"agents","running":true},'
            '{"name":"stopped","running":false}]}',
            stderr="",
        )
        default_panes = completed(
            [],
            0,
            stdout='{"result":{"panes":[{"cwd":"/repo/cms"}]}}',
            stderr="",
        )
        agent_panes = completed(
            [],
            0,
            stdout='{"result":{"panes":['
            '{"foreground_cwd":"/repo/cms.feature/backend"}]}}',
            stderr="",
        )
        with (
            mock.patch.object(portal_dev_reap.shutil, "which", return_value="herdr"),
            mock.patch.object(
                portal_dev_reap,
                "run",
                side_effect=[session_list, default_panes, agent_panes],
            ) as run_mock,
        ):
            paths, error = portal_dev_reap.herdr_active_paths()

        self.assertIsNone(error)
        self.assertEqual(paths, [Path("/repo/cms"), Path("/repo/cms.feature/backend")])
        self.assertEqual(
            run_mock.call_args_list[1].args[0],
            ["herdr", "--session", "default", "pane", "list"],
        )
        self.assertEqual(
            run_mock.call_args_list[2].args[0],
            ["herdr", "--session", "agents", "pane", "list"],
        )

    def test_audit_preserves_active_and_refuses_foreign_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 15000)
        collided = target("worktree", "/repo/cms.collided", "collided", 16000)
        orphan = target("trash", "/repo/cms/.git/wt/trash/orphan", "orphan", 17000)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=10,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start stale",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=20,
                ppid=1,
                command="process-compose",
                cwd=str(collided.path),
                identity="start collided",
                age="02:00",
                ports=(int(collided.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=21,
                ppid=10,
                command="redis-server",
                cwd=str(stale.path),
                identity="start foreign",
                age="03:00",
                ports=(int(collided.ports["REDIS_PORT"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=30,
                ppid=1,
                command="redis-server",
                cwd=str(orphan.path),
                identity="start orphan",
                age="04:00",
                ports=(int(orphan.ports["REDIS_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale, collided, orphan],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([root], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["primary"].classification, "active")
        self.assertTrue(reports["primary"].protected)
        self.assertEqual(reports["stale"].classification, "inactive")
        self.assertTrue(reports["stale"].actionable)
        self.assertEqual(reports["collided"].classification, "unknown")
        self.assertFalse(reports["collided"].actionable)
        self.assertEqual(reports["orphan"].classification, "deleted-checkout-orphan")
        self.assertTrue(reports["orphan"].actionable)

    def test_audit_allows_manager_controlled_nix_store_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17500)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=40,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start manager",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=41,
                ppid=40,
                command="worker-dashboard",
                cwd="/nix/store/example-worker-dashboard",
                identity="start worker",
                age="01:00",
                ports=(int(stale.ports["WORKER_DASHBOARD_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "inactive")
        self.assertTrue(reports["stale"].actionable)
        self.assertEqual(reports["stale"].manager_controlled_listeners[0]["pid"], 41)

    def test_audit_refuses_orphaned_unproven_dashboard_listener(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17700)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=60,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start manager",
                age="01:00",
                ports=(int(stale.ports["PC_PORT_NUM"]),),
            ),
            portal_dev_reap.ProcessRef(
                pid=61,
                ppid=1,
                command="worker-dashboard",
                cwd="/nix/store/example-worker-dashboard",
                identity="start orphan dashboard",
                age="01:00",
                ports=(int(stale.ports["WORKER_DASHBOARD_PORT"]),),
            ),
        ]
        with (
            mock.patch.object(
                portal_dev_reap, "discover_targets", return_value=[primary, stale]
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            result, _targets = portal_dev_reap.build_audit(root)

        stale_report = {item.name: item for item in result.targets}["stale"]
        self.assertEqual(stale_report.classification, "unknown")
        self.assertFalse(stale_report.actionable)
        self.assertEqual(stale_report.foreign_listeners[0]["pid"], 61)

    def test_explicit_protection_covers_work_not_visible_to_herdr(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        protected = target("worktree", "/repo/cms.protected", "protected", 17800)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=70,
                ppid=1,
                command="process-compose",
                cwd=str(protected.path),
                identity="start protected",
                age="01:00",
                ports=(int(protected.ports["PC_PORT_NUM"]),),
            )
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, protected],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            result, _targets = portal_dev_reap.build_audit(
                root, (protected.path / "backend",)
            )

        protected_report = {item.name: item for item in result.targets}["protected"]
        self.assertEqual(protected_report.classification, "protected")
        self.assertTrue(protected_report.protected)
        self.assertFalse(protected_report.actionable)

    def test_explicit_protection_refuses_unmatched_path(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        with (
            mock.patch.object(
                portal_dev_reap, "discover_targets", return_value=[primary]
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=[]
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
            self.assertRaisesRegex(portal_dev_reap.ReapError, "protected path"),
        ):
            portal_dev_reap.build_audit(root, (Path("/repo/cms.typo"),))

    def test_auxiliary_port_change_keeps_ownership_fingerprint_stable(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)

        def build_with_ports(ports: tuple[int, ...]) -> portal_dev_reap.Audit:
            process = portal_dev_reap.ProcessRef(
                pid=80,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="same start and command",
                age="01:00",
                ports=ports,
            )
            with (
                mock.patch.object(
                    portal_dev_reap,
                    "discover_targets",
                    return_value=[primary, stale],
                ),
                mock.patch.object(
                    portal_dev_reap, "listener_processes", return_value=[process]
                ),
                mock.patch.object(
                    portal_dev_reap, "herdr_active_paths", return_value=([], None)
                ),
            ):
                result, _targets = portal_dev_reap.build_audit(root)
            return result

        pc_port = int(stale.ports["PC_PORT_NUM"])
        before = build_with_ports((pc_port, 28000))
        after = build_with_ports((pc_port, 28001, 28002))
        before_report = {item.name: item for item in before.targets}["stale"]
        after_report = {item.name: item for item in after.targets}["stale"]
        self.assertTrue(before_report.actionable)
        self.assertTrue(after_report.actionable)
        self.assertEqual(before_report.fingerprint, after_report.fingerprint)

    def test_apply_skips_genuine_process_identity_replacement(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18100)
        initial = audit([report(stale, fingerprint=[[80, "old", str(stale.path)]])])
        changed = audit([report(stale, fingerprint=[[80, "new", str(stale.path)]])])
        final = audit(
            [
                report(
                    stale,
                    fingerprint=[[80, "new", str(stale.path)]],
                    actionable=False,
                    classification="unknown",
                )
            ]
        )
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[(changed, {str(stale.path): stale}), (final, {})],
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_apply_timeout_continues_without_retry_and_reports_results(self) -> None:
        root = Path("/repo/cms")
        first = target("worktree", "/repo/cms.first", "first", 18200)
        second = target("worktree", "/repo/cms.second", "second", 18300)
        first_report = report(first, fingerprint=[[81, "first", str(first.path)]])
        second_report = report(second, fingerprint=[[82, "second", str(second.path)]])
        initial = audit([first_report, second_report])
        fresh = audit([first_report, second_report])
        final = audit([])
        timeout = subprocess.TimeoutExpired(["nix", "run"], 180)
        succeeded = subprocess.CompletedProcess([], 0)
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(first.path): first, str(second.path): second}),
                    (final, {}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
            mock.patch.object(
                portal_dev_reap, "fingerprint_is_current", return_value=True
            ),
            mock.patch.object(
                portal_dev_reap,
                "cleanup_command",
                side_effect=lambda item: ["cleanup", item.name],
            ),
            mock.patch.object(
                portal_dev_reap, "run", side_effect=[timeout, succeeded]
            ) as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO) as stdout,
            mock.patch("sys.stderr", new_callable=io.StringIO) as stderr,
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        self.assertEqual(run_mock.call_count, 2)
        self.assertIn("not retrying", stderr.getvalue())
        self.assertIn("failed: cleanup timed out", stdout.getvalue())
        self.assertIn("cleanup completed", stdout.getvalue())

    def test_apply_skips_identity_replaced_after_batch_revalidation(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18350)
        stale_report = report(stale, fingerprint=[[84, "stable", str(stale.path)]])
        initial = audit([stale_report])
        fresh = audit([stale_report])
        final = audit([stale_report])
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(stale.path): stale}),
                    (final, {str(stale.path): stale}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
            mock.patch.object(
                portal_dev_reap, "fingerprint_is_current", return_value=False
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
            mock.patch("sys.stderr", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_apply_rechecks_herdr_before_each_cleanup(self) -> None:
        root = Path("/repo/cms")
        stale = target("worktree", "/repo/cms.stale", "stale", 18400)
        stale_report = report(stale, fingerprint=[[83, "stable", str(stale.path)]])
        initial = audit([stale_report])
        fresh = audit([stale_report])
        final = audit([stale_report])
        with (
            mock.patch.object(
                portal_dev_reap,
                "build_audit",
                side_effect=[
                    (fresh, {str(stale.path): stale}),
                    (final, {str(stale.path): stale}),
                ],
            ),
            mock.patch.object(
                portal_dev_reap,
                "herdr_active_paths",
                return_value=([stale.path], None),
            ),
            mock.patch.object(portal_dev_reap, "run") as run_mock,
            mock.patch("sys.stdout", new_callable=io.StringIO),
        ):
            exit_code = portal_dev_reap.apply_cleanup(root, initial)

        self.assertEqual(exit_code, 1)
        run_mock.assert_not_called()

    def test_audit_refuses_process_compose_on_an_unexpected_port(self) -> None:
        root = Path("/repo/cms")
        primary = portal_dev_reap.Target(
            kind="primary",
            path=root,
            name="primary",
            ports=dict(portal_dev_reap.PRIMARY_PORTS),
        )
        stale = target("worktree", "/repo/cms.stale", "stale", 17600)
        processes = [
            portal_dev_reap.ProcessRef(
                pid=50,
                ppid=1,
                command="process-compose",
                cwd=str(stale.path),
                identity="start mismatched manager",
                age="01:00",
                ports=(19000,),
            )
        ]
        with (
            mock.patch.object(
                portal_dev_reap,
                "discover_targets",
                return_value=[primary, stale],
            ),
            mock.patch.object(
                portal_dev_reap, "listener_processes", return_value=processes
            ),
            mock.patch.object(
                portal_dev_reap, "herdr_active_paths", return_value=([], None)
            ),
        ):
            audit, _targets = portal_dev_reap.build_audit(root)

        reports = {report.name: report for report in audit.targets}
        self.assertEqual(reports["stale"].classification, "unknown")
        self.assertFalse(reports["stale"].actionable)

    def test_cleanup_command_passes_the_validated_identity(self) -> None:
        stale = target("worktree", "/repo/cms.stale", "stale", 18000)
        with mock.patch.object(
            portal_dev_reap, "require_tool", return_value="/nix/bin/nix"
        ):
            command = portal_dev_reap.cleanup_command(stale)
        self.assertEqual(
            command[:4],
            ["/nix/bin/nix", "run", "/repo/cms.stale#portal-worktree-lifecycle", "--"],
        )
        self.assertIn("--pc-port-num", command)
        self.assertIn(stale.ports["PC_PORT_NUM"], command)


if __name__ == "__main__":
    unittest.main()
