require('plugins')
require('lsp')
require('options')
require('completion')
require('keybinds')

require('plugin/gitsigns')
require('plugin/elixir')
require('plugin/lazygit')
require('plugin/onedark')
require('plugin/lualine')
